# Generated by Django 5.0.6 on 2024-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/thumbnails/008/202/375/original/loading-circle-icon-loading-gif-loading-screen-gif-loading-spinner-gif-loading-animation-loading-free-video.jpg', max_length=5000),
        ),
    ]
