# Generated by Django 5.0.6 on 2024-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_alter_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://miro.medium.com/v2/da:true/resize:fit:630/1*ngNzwrRBDElDnf2CLF_Rbg.gif', max_length=5000),
        ),
    ]
