# Generated by Django 5.0.6 on 2024-07-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_alter_items_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_image',
        ),
    ]
